# Generated by Django 4.2.7 on 2025-11-15 00:07

import ckeditor_uploader.fields
import cloudinary.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover', cloudinary.models.CloudinaryField(help_text='Recommended size: 1200x675 pixels', max_length=255, verbose_name='image')),
                ('title', models.CharField(max_length=100000)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('snippet', models.TextField()),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Archived', 'Archived')], default='draft', max_length=10)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('body', models.TextField()),
                ('attachment', cloudinary.models.CloudinaryField(blank=True, help_text='Optional file attachment for the comment', max_length=255, null=True, verbose_name='raw')),
            ],
            options={
                'verbose_name': 'Blog Comment',
                'verbose_name_plural': 'Blog Comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField(help_text='Brief biography of the speaker')),
                ('photo', cloudinary.models.CloudinaryField(blank=True, help_text='Speaker profile photo - Recommended: 400x400 pixels', max_length=255, null=True, verbose_name='image')),
                ('website', models.URLField(blank=True)),
                ('twitter', models.CharField(blank=True, max_length=100)),
                ('linkedin', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Speaker',
                'verbose_name_plural': 'Speakers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('featured_image', cloudinary.models.CloudinaryField(help_text='Recommended size: 1200x675 pixels', max_length=255, verbose_name='image')),
                ('start_datetime', models.DateTimeField()),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(480)])),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_featured', models.BooleanField(default=False)),
                ('meeting_url', models.URLField(blank=True, help_text='Zoom/Google Meet link')),
                ('recording_url', models.URLField(blank=True, help_text='Link to webinar recording')),
            ],
            options={
                'verbose_name': 'Webinar',
                'verbose_name_plural': 'Webinars',
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='WebinarRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'cancelled')], max_length=255)),
                ('question', models.TextField(blank=True, null=True, verbose_name='Any questions for the speaker')),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.FileField(blank=True, null=True, upload_to='payment', verbose_name='Proof of Payment')),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='core.webinar')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
