# Generated by Django 4.2.7 on 2025-11-15 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_webinars', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='webinar',
            name='speakers',
            field=models.ManyToManyField(related_name='webinars', to='core.speaker'),
        ),
        migrations.AddField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.blog'),
        ),
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category'),
        ),
        migrations.AlterUniqueTogether(
            name='webinarregistration',
            unique_together={('webinar', 'email')},
        ),
        migrations.AddIndex(
            model_name='webinar',
            index=models.Index(fields=['status', 'start_datetime'], name='core_webina_status_5c286e_idx'),
        ),
        migrations.AddIndex(
            model_name='webinar',
            index=models.Index(fields=['is_featured', 'status'], name='core_webina_is_feat_7eb7c6_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['status', 'created_at'], name='core_blog_status_549f03_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['is_verified', 'status'], name='core_blog_is_veri_5967ea_idx'),
        ),
    ]
